### ISSUE TITLE
tes3mp-server fails to build on Mint 18.1

### ISSUE THREAD

**Issue by uckfayer** [GrimKriegor/TES3MP-deploy#8]
When running the script it always fails at the same point. I'm running Linux Mint 18.1.
Error:
```

[ 96%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Cell.cpp.o
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp: In member function ‘bool mwmp::DedicatedActor::hasItem(std::__cxx11::string, int)’:
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:228:28: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                            ^
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:228:61: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                                                             ^
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp: In member function ‘void mwmp::DedicatedActor::equipItem(std::__cxx11::string, int)’:
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:28: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                            ^
/home/master/Games/TES3MP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:61: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                                                             ^
[ 96%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/CellController.cpp.o
[ 96%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/MechanicsHelper.cpp.o
apps/openmw/CMakeFiles/tes3mp.dir/build.make:6038: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o' failed
make[2]: *** [apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:501: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/all' failed
make[1]: *** [apps/openmw/CMakeFiles/tes3mp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by GrimKriegor** [comment]
Hello there, thanks for the bug report.

The multiplayer component of TES3MP uses some newer C++ features which requires at least GCC 6 to build. I believe that version of Mint has GCC 4.9.

This requirement is still undocumented since I haven't decided how to elegantly go about it.

Upgrading your toolchain or testing one of the [new prebuilt packages](https://grimkriegor.zalkeen.us/public/tes3mp%2dGNU%2bLinux%2dx86%5f64%2drelease%2d0.6.0%2df61664ff6d%2dRC4.tar.gz) will most likely allow you to play.

Good luck!

**Comment by GrimKriegor** [comment]
Fixed by https://github.com/GrimKriegor/TES3MP-deploy/commit/1742a63774caad31b559b12a1ca38bc68ca8d25c
